### ISSUE TITLE
nodeconf.org

### ISSUE THREAD

**Issue by thebergamo** [nodeconf/website#10]
Hello everybody!

I just buy this domain for using in NodeConfBR - http://br.nodeconf.org

And, I think in an idea why not using this domain for serving for whatever you want nodeconfs?

You can just create an CNAME with an wildcard for nodeconf.org.  The idea is based on http://js.org.

I don't create an website yet, but what you think about it guys?

**Comment by mikeal** [comment]
I have nodeconf.com and it's setup so that any repo's gh-pages in this org can be at a subdomain :)

**Comment by thebergamo** [comment]
Thats good =D

But, I think using this for any other orgs or repos any people who using a gh-pages you know?
