### ISSUE TITLE
Speaker Pic Adjustment

### ISSUE THREAD

**Issue by mikeal** [nodeconf/website#4]
@thefoxis heya, I added some more speaker pics but I don't know what blue filter you use on them :)

**Comment by thefoxis** [comment]
@mikeal&mdash;will adjust, do you have the short paragraphs for talks too?

**Comment by mikeal** [comment]
not yet, I can write them up in a bit :)

**Comment by mikeal** [comment]
- Chris Williams: serial-port and the birth of javascript IoT.
- Fedor Indutny: the future of Streams in C++ on io.js.
- Rod Vagg: a reliable native ecosystem with `nan`.
- Substack: the cyber wizards guide to free education.
- Trevor Norris: best practices learned through blood sweat and tears for connecting C++ and JS.
